apiVersion: v1
kind: Pod
metadata:
  name: fiopod
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: fio
      image: mayadata/fio
      args: ["sleep", "1000000"]
      volumeMounts:
        - mountPath: /volume
          name: ephemeralvolume
  volumes:
    - name: ephemeralvolume
      ephemeral:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 10Gi
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            storageClassName: local
